## Single-Input Perceptron for Walking Prediction

This code demonstrates a simple single-input perceptron algorithm learning to predict whether someone will walk or stop based on the presence of streetlights:

**Initialization:**

- `weights`: An array of weights for each input feature (streetlights). Initially, all are set to 0.5.
- `alpha`: Learning rate, controlling how much weights are updated in each iteration.
- `streetlights`: A 2D array representing streetlight observations, where 1 indicates a light on and 0 is off.
- `walk_vs_stop`: An array indicating the actual behavior (walk=1, stop=0) for each observation.
- `input`: We only use the first observation from `streetlights` for demonstration.

**Training Loop:**

- **Each iteration:**
    - `pred`: Calculate the predicted outcome (0 or 1) using the current weights and input.
    - `error`: Calculate the squared error between the prediction and the actual behavior.
    - `delta`: Calculate the difference between the predicted and actual value.
    - `weights`: Update weights based on the learning rate, input, and the error (delta).
    - `print`: Print the current iteration, error, and prediction.

In [1]:
# one input
import numpy as np
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array([   [1, 0, 1],
                            [0, 1, 1],
                            [0, 0, 1],
                            [1, 1, 1],
                            [0, 1, 1],
                            [1, 0, 1]])

walk_vs_stop = np.array([0, 1, 0, 1, 1, 0])
input = streetlights[0] # [1, 0, 1]
true = walk_vs_stop[0] # 0

for iteration in range(20):
    pred = input.dot(weights)
    error = (true - pred) ** 2
    delta = pred - true
    weights = weights - (alpha * (input * delta))
    print(f"Iteration {iteration+1}: " +"Error: " + str(error))


Iteration 1: Error: 0.03999999999999998
Iteration 2: Error: 0.025599999999999973
Iteration 3: Error: 0.01638399999999997
Iteration 4: Error: 0.010485759999999964
Iteration 5: Error: 0.006710886399999962
Iteration 6: Error: 0.004294967295999976
Iteration 7: Error: 0.002748779069439994
Iteration 8: Error: 0.0017592186044416036
Iteration 9: Error: 0.0011258999068426293
Iteration 10: Error: 0.0007205759403792803
Iteration 11: Error: 0.0004611686018427356
Iteration 12: Error: 0.0002951479051793508
Iteration 13: Error: 0.00018889465931478573
Iteration 14: Error: 0.00012089258196146188
Iteration 15: Error: 7.737125245533561e-05
Iteration 16: Error: 4.951760157141604e-05
Iteration 17: Error: 3.169126500570676e-05
Iteration 18: Error: 2.028240960365233e-05
Iteration 19: Error: 1.298074214633813e-05
Iteration 20: Error: 8.307674973656916e-06


## Walking Prediction with Perceptron and Whole Dataset Training

**Initialization:**

- `weights`: Same as before, initial weights for each streetlight feature.
- `alpha`: Learning rate for weight updates.
- `streetlights`: 2D array representing streetlight observations (1=on, 0=off).
- `walk_vs_stop`: Array indicating actual behavior (walk=1, stop=0).

**Training Loop:**

- **Each iteration:**
    - `error_for_all`: Initialize total error for the iteration.
    - **Loop through each observation:**
        - `input`: Select the current streetlight observation.
        - `true`: Get the corresponding actual behavior.
        - `pred`: Calculate the predicted outcome using current weights and input.
        - `error`: Calculate squared error between prediction and true value.
        - Add error to `error_for_all`.
        - `delta`: Calculate the difference between prediction and true value.
        - Update weights based on learning rate, input, and error (delta).
    - Print the iteration, total error for the iteration.

**Prediction:**

- Create a test input with all values set to 1 (represents all streetlights on).
- Calculate the dot product of test input and updated weights.
- If the result is greater than 0.5, predict "Walk", otherwise "Stop".

In [5]:
# whole dataset training
import numpy as np
weights = np.array([0.5, 0.48, -0.7])
alpha = 0.1

streetlights = np.array([   [1, 0, 1],
                            [0, 1, 1],
                            [0, 0, 1],
                            [1, 1, 1],
                            [0, 1, 1],
                            [1, 0, 1]])

walk_vs_stop = np.array([0, 1, 0, 1, 1, 0])


for iteration in range(25):
    error_for_all = 0
    for index in range(len(walk_vs_stop)): # 6
        input = streetlights[index]
        true = walk_vs_stop[index]
        pred = input.dot(weights)
        error = (pred - true) ** 2
        error_for_all += error
        delta = pred - true
        weights = weights - (alpha * (input * delta))
        #print(" Prediction: " + str(pred))
    print(f"Iteration {iteration+1}: " +"Error: " + str(error_for_all) )
test = [0, 1, 1] * weights
if sum(test) > 0.5:
    print('Walk')
else:
    print('Stop')


Iteration 1: Error: 2.6561231104
Iteration 2: Error: 0.9628701776715985
Iteration 3: Error: 0.5509165866836796
Iteration 4: Error: 0.36445836852222424
Iteration 5: Error: 0.25167686620798957
Iteration 6: Error: 0.17797575048089034
Iteration 7: Error: 0.1286446073342217
Iteration 8: Error: 0.0951103695047621
Iteration 9: Error: 0.07194564247043442
Iteration 10: Error: 0.05564914990717743
Iteration 11: Error: 0.04394763937673941
Iteration 12: Error: 0.03535796705094847
Iteration 13: Error: 0.02890700056547436
Iteration 14: Error: 0.023951660591138853
Iteration 15: Error: 0.020063105176016106
Iteration 16: Error: 0.016952094519447077
Iteration 17: Error: 0.014420818295271235
Iteration 18: Error: 0.012331739998443647
Iteration 19: Error: 0.010587393171639842
Iteration 20: Error: 0.009117233405426495
Iteration 21: Error: 0.007869042269042082
Iteration 22: Error: 0.006803273214640504
Iteration 23: Error: 0.00588930354183781
Iteration 24: Error: 0.005102925256117271
Iteration 25: Error: 0.004

## Looping over the Dataset with Bias and without

In [5]:
## Without Biasses
np.random.seed(1)
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]]) # inputs
walk_vs_stop = np.array([[1, 1, 0, 0]]).T # outputs
def relu(x):
    return (x > 0) * x
def relu2deriv(output):
    return output > 0
# Initialize random weights between -1 and 1, biases at zero
hidden_size = 4
output_size = 1
input_size = 3
alpha = 0.2
weights_0_1 = 2 * np.random.random((input_size, hidden_size)) - 1 # 3x4
weights_1_2 = 2 * np.random.random((hidden_size, output_size)) - 1 # 4x1
for iteration in range(60):
    layer_2_error = 0
    for i in range(len(walk_vs_stop)):
        layer_0 = streetlights[i:i+1] # 1x3
        layer_1 = relu(np.dot(layer_0, weights_0_1) + b) # 1x3 * 3x4 = 1x4
        layer_2 = np.dot(layer_1, weights_1_2) # 1x4 * 4x1 = 1x1
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])     # scalar - scalar / 1x1 - 1x1 = single value
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1) # 1x1 * 1x4 = 1x4 (weighted sum/dot product) --> 1x4 * 1x4 (elementwise multiplication)
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta) # weights_1_2 + 0.2 * (4x1 * 1x1) = weights_1_2 + 4x1 = new weights
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta) # weights_0_1 + 0.2 * (3x1 * 1x4) = weights_0_1 + 3x4 = new weights
    if iteration % 10 == 9:
        print(f"Error: {layer_2_error}")




Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


In [3]:
## With Biasses
np.random.seed(1)

streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]])  # inputs
walk_vs_stop = np.array([[1, 1, 0, 0]]).T  # outputs

def relu(x):
    return (x > 0) * x

def relu2deriv(output):
    return output > 0

# Initialize random weights and biases
hidden_size = 4
output_size = 1
input_size = 3
alpha = 0.2

weights_0_1 = 2 * np.random.random((input_size, hidden_size)) - 1  # 3x4
weights_1_2 = 2 * np.random.random((hidden_size, output_size)) - 1  # 4x1
biases_0_1 = np.ones((1, hidden_size))  # 1x4
biases_1_2 = np.ones((1, output_size))  # 1x1

for iteration in range(60):
    layer_2_error = 0
    for i in range(len(walk_vs_stop)):
        layer_0 = streetlights[i:i+1]  # 1x3
        layer_1 = relu(np.dot(layer_0, weights_0_1) + biases_0_1)  # 1x3 * 3x4 + 1x4 = 1x4
        layer_2 = np.dot(layer_1, weights_1_2) + biases_1_2  # 1x4 * 4x1 + 1x1 = 1x1
        layer_2_error += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1])  # 1x1 - 1x1 = 1x1
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1)  # 1x1 * 1x4 = 1x4
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta)  # 4x1 + 4x1 = 4x1
        biases_1_2 -= alpha * layer_2_delta  # 1x1 + 1x1 = 1x1
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta)  # 3x4 + 3x4 = 3x4
        biases_0_1 -= alpha * layer_1_delta  # 1x4 + 1x4 = 1x4
    if iteration % 10 == 9:
        print(f"Error: {layer_2_error}")


Error: 0.4645221167080672
Error: 0.1673265734674444
Error: 0.016549482150906406
Error: 2.256711580124347e-05
Error: 8.990664787657676e-09
Error: 3.613913005749867e-12


: 


![picture 1](images/caab1d76386e28df4646c8f3b72726d28ad9baf51474cc63d6b6151d94bd5b10.png)


In [10]:
import numpy as np
np.random.seed(1)
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]]) # inputs
walk_vs_stop = np.array([[1, 1, 0, 0]]).T # outputs
def relu(x):
    return (x > 0) * x
def relu2deriv(output):
    return output > 0
# Initialize random weights between -1 and 1, biases at zero
hidden_size = 4
output_size = 1
input_size = 3
alpha = 0.2
weights_0_1 = 2 * np.random.random((input_size, hidden_size)) - 1 # 3x4
weights_1_2 = 2 * np.random.random((hidden_size, output_size)) - 1 # 4x1

for iteration in range(60):
    error_of_layer_3 = 0
    for i in range(len(walk_vs_stop)):
        layer_0 = streetlights[i:i+1] # 1x3
        layer_1 = relu(np.dot(layer_0, weights_0_1)) # 1x3 * 3x4 = 1x4
        layer_2 = np.dot(layer_1, weights_1_2) # 1x3 * 3x1 = 1x1
        error_of_layer_3 += np.sum((layer_2 - walk_vs_stop[i:i+1]) ** 2)
        layer_2_delta = (layer_2 - walk_vs_stop[i:i+1]) # 1x1
        layer_1_delta = layer_2_delta.dot(weights_1_2.T) * relu2deriv(layer_1) # 1x1 * 1x3 = 1x3
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta) # 3x1 * 1x1 = 3x1 
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta) # 3x1 * 1x3 = 3x3 
    if iteration % 10 == 9:
        print(f"Error: {error_of_layer_3}")

Error: 0.6342311598444467
Error: 0.35838407676317513
Error: 0.0830183113303298
Error: 0.006467054957103705
Error: 0.0003292669000750734
Error: 1.5055622665134859e-05


## Making the Network more bigger by adding another layer

In [19]:
np.random.seed(1)
streetlights = np.array([[1, 0, 1],
                         [0, 1, 1],
                         [0, 0, 1],
                         [1, 1, 1]]) # inputs
walk_vs_stop = np.array([[1, 1, 0, 0]]).T # outputs
def relu(x):
    return (x > 0) * x
def relu2deriv(output):
    return output > 0
# Initialize random weights between -1 and 1, biases at zero
hidden_size = 4
output_size = 1
input_size = 3
alpha = 0.2
weights_0_1 = 2 * np.random.random((input_size, hidden_size)) - 1 # 3x4
weights_1_2 = 2 * np.random.random((hidden_size, hidden_size)) - 1 # 4x4
weights_2_3 = 2 * np.random.random((hidden_size, output_size)) - 1 # 4x1

for iteration in range(120):
    error_of_layer_3 = 0
    for i in range(len(walk_vs_stop)):
        layer_0 = streetlights[i:i+1] # 1x3
        layer_1 = relu(np.dot(layer_0, weights_0_1)) # 1x3 * 3x4 = 1x4
        layer_2 = relu(np.dot(layer_1, weights_1_2)) # 1x4 * 4x4 = 1x4
        layer_3 = np.dot(layer_2, weights_2_3) # 1x4 * 4x1 = 1x1
        error_of_layer_3 += np.sum((layer_3 - walk_vs_stop[i:i+1]) ** 2)
        layer_3_delta = (layer_3 - walk_vs_stop[i:i+1])
        layer_2_delta = np.dot(layer_3_delta, weights_2_3.T) * relu2deriv(layer_1) # 1x1 * 4x1 = 1x4
        layer_1_delta = np.dot(layer_2_delta, weights_1_2) * relu2deriv(layer_1) # 1x4 * 4x4 = 1x4
        weights_2_3 -= alpha * layer_2.T.dot(layer_3_delta) # 4x1 * 1x1 = 4x1
        weights_1_2 -= alpha * layer_1.T.dot(layer_2_delta) # 4x1 * 1x4 = 4x4
        weights_0_1 -= alpha * layer_0.T.dot(layer_1_delta) # 3x1 * 1x4 = 3x4
    if iteration % 10 == 9:
        print(f"Error: {error_of_layer_3}")

Error: 0.9367803226725138
Error: 0.5592374543970701
Error: 0.4834911798273517
Error: 0.41394429957198897
Error: 0.34787318445799054
Error: 0.2834789212043714
Error: 0.22372188658165565
Error: 0.17117098863030095
Error: 0.12724947233840095
Error: 0.09212655425221168
Error: 0.06495888297673076
Error: 0.04414722216643945


In [7]:
np.random.seed(1)
test1 = 2 * np.random.random((1,4)) +1
test2 = 2 * np.random.random((1,4)) +1
print(test1, end='\n\n')
print(test2, end='\n\n')
print(test1 * test2)
print(8.91260736926666e-06 < 1.5055622665134859e-05)

[[1.83404401 2.44064899 1.00022875 1.60466515]]

[[1.29351178 1.18467719 1.37252042 1.69112145]]

[[2.37235753 2.89138118 1.37283439 2.71368365]]
True


In [37]:
test1 = 2 * np.random.random((1,4)) + 1
test2 = 2 * np.random.random((4,1)) + 1
test1.dot(test2)

array([[15.83792851]])