In [1]:
weight = 0.1
def neural_network(input, weight):
    prediction = input * weight
    return prediction

toes = [8.5, 9.5, 10, 9]
input = toes[0]
pred = neural_network(input, weight)
print(pred)

0.8500000000000001


In [2]:
weights = [0.1, 0.2, 0]
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = [toes[0], wlrec[0], nfans[0]]

def w_sum(a, b):
    assert (len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def neural_network(input, weight):
    prediction = w_sum(input, weight)
    return prediction
prediction = neural_network(input, weights)
print(prediction)

0.9800000000000001


In [3]:
def elementwise_multiplication(vec_a, vec_b):
    """Element-wise multiplication of two vectors."""
    assert (len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] * vec_b[i])
    return output

def elementwise_addition(vec_a, vec_b):
    """Element-wise addition of two vectors."""
    assert (len(vec_a) == len(vec_b))
    output = []
    for i in range(len(vec_a)):
        output.append(vec_a[i] + vec_b[i])
    return output

def vector_sum(vec):
    """Sums all the elements of a given list"""
    return sum(vec)

def vector_average(vec):
    return sum(vec) / len(vec)


In [4]:
output = elementwise_multiplication(input, weights)
pred = vector_sum(output)
print(pred)

0.9800000000000001


In [5]:
import numpy as np

weights = np.array([0.1, 0.2, 0])
def neural_network(input, weight):
    prediction = np.dot(input, weight)
    return prediction

toes = np.array([8.5, 9.5, 9.9, 9.0])
wlrec = np.array([0.65, 0.8, 0.8, 0.9])
n_fans = np.array([1.2, 1.3, 0.5, 1.0])
input = np.array([toes[0], wlrec[0], nfans[0]])
prediction = neural_network(input, weights)
print(prediction)

0.9800000000000001


In [7]:
# Neural Network with one input and multiple outpus
def ele_mul(number, vector):
    output = [0, 0, 0]
    assert (len(output) == len(vector))
    for i in range(len(vector)):
        output[i] = number * vector[i]
    return output

def neural_network(input, weight):
    prediction = ele_mul(input, weight)
    return prediction

input = wlrec[0]
weights = [0.3, 0.2, 0.9]
pred = neural_network(input, weights)
print(pred)



[0.195, 0.13, 0.5850000000000001]


In [10]:
# Neural Network with multiple inputs and multiple outputs
def w_sum(a, b):
    assert (len(a) == len(b))
    output = 0
    for i in range(len(a)):
        output += a[i] * b[i]
    return output

def vect_mat_mul(vect, matrix):
    assert (len(vect) == len(matrix))
    output = [0, 0, 0]

    for i in range(len(vect)):
        output[i] = w_sum(vect, matrix[i])
    return output

def neural_network(input, weight):
    prediction = vect_mat_mul(input, weight)
    return prediction

weights = [[0.1, 0.1, -0.3], # hurt?
            [0.1, 0.2, 0.0],  # win?
            [0.0, 1.3, 0.1]]  # sad?
toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]

input = [toes[0], wlrec[0], nfans[0]]
pred = neural_network(input, weights)
print(pred)

[0.555, 0.9800000000000001, 0.9650000000000001]


In [11]:
# Neural Network with multiple inputs and multiple outputs and multiple layers
ih_wgt = [[0.1, 0.2, -0.1],
          [-0.1, 0.1, 0.9],
          [0.1, 0.4, 0.1]]
hp_wgt = [[0.3, 1.1, -0.3],
          [0.1, 0.2, 0.0],
          [0.0, 1.3, 0.1]]

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = vect_mat_mul(input, weights[0])
    pred = vect_mat_mul(hid, weights[1])
    return pred

pred = neural_network(input, weights)
print(pred)

[0.21350000000000002, 0.14500000000000002, 0.5065]


In [15]:
# Numpy Version
# Neural Network with multiple inputs and multiple outputs and multiple layers
ih_wgt = np.array([[0.1, 0.2, -0.1],
                   [-0.1, 0.1, 0.9],
                   [0.1, 0.4, 0.1]])

hp_wgt = np.array([[0.3, 1.1, -0.3],
                   [0.1, 0.2, 0.0],
                   [0.0, 1.3, 0.1]])

weights = [ih_wgt, hp_wgt]

def neural_network(input, weights):
    hid = input.dot(weights[0])
    pred = hid.dot(weights[1])
    return pred

toes = [8.5, 9.5, 9.9, 9.0]
wlrec = [0.65, 0.8, 0.8, 0.9]
nfans = [1.2, 1.3, 0.5, 1.0]
input = np.array([toes[0], wlrec[0], nfans[0]])
pred = neural_network(input, weights)
print(pred)


[ 0.496  1.256 -0.286]


In [28]:
a = np.array([0, 1, 2, 3])
b = np.array([4, 5, 6, 7])
c = np.array([[0, 1, 2, 3],
             [4, 5, 6, 7]])

d = np.zeros((2, 4))
e = np.random.rand(2, 5)
# print(a)
# print(b)
# print(c)
# print(d)
# print(e)
print(a * 0.1)
print(c * 0.2)
print(a * b)
print('---')
print(a * b * 0.2)
print(a * c)
#print(a * e) # operands could not be broadcast together with shapes (4,) (2,5) 


[0.  0.1 0.2 0.3]
[[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]]
[ 0  5 12 21]
---
[0.  1.  2.4 4.2]
[[ 0  1  4  9]
 [ 0  5 12 21]]


In [73]:
a = np.random.rand(2,3)
b = np.random.rand(2,3)
#c = a.dot(b)
x = a * b
#print(c.shape)
print(x.shape)

(2, 3)


In [78]:
a = np.array([[1, 2, 3],
             [4, 5, 6]]) # 2 x 3

b = np.array([[1, 2, 3], # 3 x 3
              [4, 5, 6,],
              [7, 8, 9]])

print(a.dot(b))

[[30 36 42]
 [66 81 96]]
